name: Node.js CI

on: 
  pull_request:
    branches: 
      - master

jobs:
  build:
    strategy:
      matrix:
        node: [8.x, 10.x, 12.x]
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    
    - run: npm ci
      
    - run: npm run build --if-present
      
    - run: npm test
